import type { NextPage } from 'next';
import Head from 'next/head';
import { ConnectWallet, FileUpload } from '../components';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>NFT Disseminate</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>NFT Disseminate</h1>
				<ConnectWallet />
				<FileUpload />
			</main>
		</div>
	);
};

export default Home;
